export const FETCH_PLAYLISTS_LOADING = 'FETCH_PLAYLISTS_LOADING';
export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';
export const FETCH_PLAYLISTS_FAILURE = 'FETCH_PLAYLISTS_FAILURE';

export const ACTIVATE_LOGGED_IN = 'ACTIVATE_LOGGED_IN';
export const ACTIVATE_DEMO = 'ACTIVATE_DEMO';

export const CHOOSE_NEW_PLAYLIST = 'CHOOSE_NEW_PLAYLIST';
export const RESTART_APP = 'RESTART_APP';

export const PLAYLIST_CHOSEN_TRACK_INFO_LOADING = 'PLAYLIST_CHOSEN_TRACK_INFO_LOADING';
export const FETCH_TRACKS_INFO_SUCCESS = 'FETCH_TRACKS_INFO_SUCCESS';
export const FETCH_TRACKS_INFO_FAILURE = 'FETCH_TRACKS_INFO_FAILURE';

export const FETCH_COLLABORATOR_INFO_SUCCESS = 'FETCH_COLLABORATOR_INFO_SUCCESS';
export const FETCH_COLLABORATOR_INFO_FAILURE = 'FETCH_COLLABORATOR_INFO_FAILURE';
export const FETCH_COLLABORATOR_AF_AWARDS_SUCCESS = 'FETCH_COLLABORATOR_AF_AWARDS_SUCCESS';
export const FETCH_COLLABORATOR_AF_AWARDS_FAILURE = 'FETCH_COLLABORATOR_AF_AWARDS_FAILURE';

export const ACTIVATE_COLLABORATORS = 'ACTIVATE_COLLABORATORS';
export const TOGGLE_COLLABORATOR_CARD = 'TOGGLE_COLLABORATOR_CARD';